import colorama
from colorama import Fore, Back, Style
print(f"{Fore.WHITE}┌────────────────────────────┐")
print(f"{Fore.WHITE}|                        {Fore.BLUE}- {Fore.RED}X {Fore.WHITE}|")
print(f"{Fore.WHITE}┌────────────────────────────┐")
print(f"{Fore.WHITE}|   {Fore.GREEN}TERM:    {Fore.YELLOW}██╗             {Fore.WHITE}|")
print(f"{Fore.WHITE}|            {Fore.YELLOW}██║             {Fore.WHITE}|")
print(f"{Fore.WHITE}|            {Fore.YELLOW}██║             {Fore.WHITE}|")
print(f"{Fore.WHITE}|            {Fore.YELLOW}██║             {Fore.WHITE}|")
print(f"{Fore.WHITE}|            {Fore.YELLOW}██║             {Fore.WHITE}|")
print(f"{Fore.WHITE}|            {Fore.YELLOW}███████╗        {Fore.WHITE}|")
print(f"{Fore.WHITE}|            {Fore.YELLOW}╚══════╝        {Fore.WHITE}|")
print(f"{Fore.WHITE}|                            |")
print(f"{Fore.WHITE}|                            |")
print(f"{Fore.WHITE}└────────────────────────────┘")
print(f"{Fore.WHITE}TERM:                                                 ")
print(f"{Fore.YELLOW}     ██╗     █████╗  ██████╗ █████╗██████╗ ██╗   ██╗███╗   ██╗████████╗██╗  ██╗")
print(f"{Fore.YELLOW}     ██║     ██╔══██╗██╔══██╗  ██║ ██╔══██╗╚██╗ ██╔╝████╗  ██║╚══██╔══╝██║  ██║")
print(f"{Fore.YELLOW}     ██║     ███████║██████╦╝  ██║ ██████╦╝ ╚████╔╝ ██╔██╗ ██║   ██║   ███████║")
print(f"{Fore.YELLOW}     ██║     ██╔══██║██╔══██╗  ██║ ██╔══██╗  ╚██╔╝  ██║╚██╗██║   ██║   ██╔══██║")
print(f"{Fore.YELLOW}     ██║     ██║  ██║██████╦╝█████╗██║  ██║   ██║   ██║ ╚████║   ██║   ██║  ██║")
print(f"{Fore.YELLOW}     ███████╗╚═╝  ╚═╝╚═════╝ ╚════╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝   ╚═╝   ╚═╝  ╚═╝")
print(f"{Fore.YELLOW}     ╚══════╝")